version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: akems_db
    environment:
      POSTGRES_USER: akems_user
      POSTGRES_PASSWORD: akems_password
      POSTGRES_DB: akems
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: akems_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
