'use client';

import { useState } from 'react';
import Link from 'next/link';
import { FileSpreadsheet, Map, ClipboardCheck, Contact, UserCheck, EyeOff, ShieldCheck, BarChart3, Info, X } from 'lucide-react';

const offlineTools = [
  {
    id: 'question-paper',
    title: 'Question Paper Generator',
    shortDesc: 'Upload question banks to generate randomized exam papers with digital watermarking & encrypted export.',
    detailDesc: 'How it works: Select a question bank CSV. The tool randomly selects questions based on your difficulty blueprint. It then generates a Word/PDF document and embeds a hidden digital watermark to prevent leaks. The entire process happens locally in your browser RAM.',
    icon: FileSpreadsheet,
    color: 'blue',
    link: '/offline-generator/question-paper'
  },
  {
    id: 'seating',
    title: 'Seating Arrangement',
    shortDesc: 'Upload student lists and room capacities to auto-generate seating plans and door displays.',
    detailDesc: 'How it works: Provide an Excel file of student roll numbers and a list of available rooms with capacities. The algorithm distributes students to prevent same-course students from sitting adjacent to each other. Generates printable PDFs for room doors and invigilators.',
    icon: Map,
    color: 'emerald',
    link: '/offline-generator/seating'
  },
  {
    id: 'results',
    title: 'Result Compiler',
    shortDesc: 'Merge subject marks from multiple Excel files securely to compute pass/fail results.',
    detailDesc: 'How it works: Upload the raw marks Excel sheets from different departments (e.g. Anatomy, Physiology, Biochemistry). The tool merges them based on Roll Number, applies NMC passing criteria (e.g. 50% aggregate), and outputs a final Master Result sheet.',
    icon: ClipboardCheck,
    color: 'amber',
    link: '/offline-generator/results'
  },
  {
    id: 'hall-tickets',
    title: 'Hall Ticket Generator',
    shortDesc: 'Upload student lists and timetables to auto-generate printable Admit Cards.',
    detailDesc: 'How it works: Upload a CSV of eligible students and the exam timetable. The generator uses a template to create a multi-page PDF containing a unique Admit Card with QR codes for every student, ready for bulk printing.',
    icon: Contact,
    color: 'pink',
    link: '/offline-generator/hall-tickets'
  },
  {
    id: 'invigilators',
    title: 'Smart Duty Roster',
    shortDesc: 'Fairly balance and assign faculty to examination rooms securely.',
    detailDesc: 'How it works: Input a list of available faculty and exam sessions. The algorithm assigns duties while ensuring no faculty member exceeds max consecutive duties and prevents conflicts (e.g. assigning an Anatomy professor to invigilate an Anatomy exam).',
    icon: UserCheck,
    color: 'cyan',
    link: '/offline-generator/invigilators'
  },
  {
    id: 'double-blind',
    title: 'Double-Blind Evaluation',
    shortDesc: 'Generate fictitious roll numbers for unbiased grading and securely decode them for final results.',
    detailDesc: 'How it works: Upload the real student list. The tool generates random fictitious roll numbers and creates a mapping file (which you save securely). Print the fictitious numbers on answer sheets. After grading, upload the marks and the mapping file to decode back to real roll numbers.',
    icon: EyeOff,
    color: 'indigo',
    link: '/offline-generator/double-blind'
  },
  {
    id: 'strong-room',
    title: 'Strong Room Tracking',
    shortDesc: 'Generate QR codes for physical answer sheet bundles and track their chain of custody.',
    detailDesc: 'How it works: Before exams, generate bulk QR codes for answer sheet envelopes. Scan them using a barcode scanner connected to your PC to log when bundles are checked in or out of the Strong Room. Logs are saved locally as CSV.',
    icon: ShieldCheck,
    color: 'violet',
    link: '/offline-generator/strong-room'
  },
  {
    id: 'nmc-reports',
    title: 'NMC Compliance',
    shortDesc: 'Perform Item Analysis (Difficulty/Discrimination index) and generate NMC statistical reports.',
    detailDesc: 'How it works: Upload student responses for Multiple Choice Questions. The tool computes the Facility Value (Difficulty Index) and Discrimination Index for each question, identifying poorly constructed questions to meet NMC guidelines.',
    icon: BarChart3,
    color: 'rose',
    link: '/offline-generator/nmc-reports'
  },
  {
    id: 'decoder',
    title: 'Printing Press Decoder',
    shortDesc: 'Securely decrypt .enc files generated by the Question Paper generator for printing.',
    detailDesc: 'How it works: This tool is meant for the Printing Press. Upload the encrypted .enc file received from the Dean. The system locally decodes it using Base64/AES decryption and provides a clean interface to print the physical copies.',
    icon: ShieldCheck,
    color: 'slate',
    link: '/offline-generator/decoder'
  }
];

export default function OfflineToolsPage() {
  const [activeInfo, setActiveInfo] = useState<string | null>(null);

  const toggleInfo = (e: React.MouseEvent, id: string) => {
    e.preventDefault();
    e.stopPropagation();
    setActiveInfo(activeInfo === id ? null : id);
  };

  return (
    <div className="p-8 max-w-7xl mx-auto animate-fade-in-up">
      <div className="mb-10">
        <h1 className="text-3xl font-bold text-slate-900 mb-2 flex items-center gap-3">
          Offline Tools for Dean
          <div className="relative group">
            <Info size={24} className="text-slate-400 hover:text-blue-500 cursor-help" />
            <div className="absolute left-0 bottom-full mb-2 w-80 bg-slate-800 text-white text-sm rounded-lg p-4 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-50 shadow-xl font-normal text-left leading-relaxed">
              <strong>100% Offline Architecture:</strong><br/>
              • These tools run entirely inside your browser's RAM.<br/>
              • No student data, files, or marks are ever uploaded to any internet server.<br/>
              • You can disconnect your computer from the Wi-Fi and these tools will still work perfectly.
              <div className="absolute top-full left-4 border-4 border-transparent border-t-slate-800"></div>
            </div>
          </div>
        </h1>
        <p className="text-slate-500">
          Secure, locally-processed tools that operate without an internet connection. 
          No data is uploaded to any server.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
        {offlineTools.map((tool) => (
          <Link 
            key={tool.id}
            href={tool.link} 
            className={`glass p-6 rounded-2xl border transition-all group block cursor-pointer relative overflow-hidden ${
              activeInfo === tool.id 
                ? `border-${tool.color}-400 shadow-lg shadow-${tool.color}-500/20 bg-white` 
                : `border-slate-200 hover:border-${tool.color}-300 hover:bg-slate-50`
            }`}
          >
            <div className="flex justify-between items-start mb-4">
              <div className={`w-12 h-12 rounded-xl bg-${tool.color}-50 flex items-center justify-center group-hover:scale-110 transition-transform`}>
                <tool.icon className={`text-${tool.color}-600`} size={24} />
              </div>
              <button 
                onClick={(e) => toggleInfo(e, tool.id)}
                className={`p-2 rounded-full transition-colors ${
                  activeInfo === tool.id 
                    ? `bg-${tool.color}-100 text-${tool.color}-700` 
                    : `text-slate-400 hover:bg-slate-100 hover:text-${tool.color}-600`
                }`}
                title="How it works"
              >
                {activeInfo === tool.id ? <X size={18} /> : <Info size={18} />}
              </button>
            </div>
            
            <h2 className="text-xl font-bold text-slate-900 mb-2">{tool.title}</h2>
            
            <div className="relative">
              <p className={`text-sm transition-all duration-300 ${activeInfo === tool.id ? 'opacity-0 h-0 overflow-hidden' : 'opacity-100 text-slate-500'}`}>
                {tool.shortDesc}
              </p>
              
              <div className={`text-sm transition-all duration-300 ${activeInfo === tool.id ? 'opacity-100' : 'opacity-0 h-0 overflow-hidden absolute top-0 left-0'}`}>
                <div className={`p-4 rounded-xl bg-${tool.color}-50 border border-${tool.color}-100 text-${tool.color}-900`}>
                  <strong>How it works:</strong>
                  <p className="mt-1">{tool.detailDesc.replace('How it works: ', '')}</p>
                </div>
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}
